### ISSUE TITLE
Linebreaks lost

### ISSUE THREAD

**Issue by alexbowers** [mnapoli/externals#15] opened 2016-12-02 13:45 UTC
http://externals.io/thread/534

source: http://externals.io/email/13334/source

**Comment by mnapoli** [comment] 2016-12-04 20:54
Thanks for the report, that's indeed very curious. I wonder if it's because of the `<?php` tag. There's this test that is slightly related but it doesn't seem to explain the problem. If you manage to write a failing test or understand what's happening I'm interested :)

**Comment by tomzx** [comment] 2017-01-16 01:47
@mnapoli It appears the content is still properly formatted, but it would require either all of the content (or more specifically the code) be within a `pre` tag, that each line of code receive its own `br` tag or applying the `white-space: pre` style to the appropriate elements.

I haven't looked at much of `externals` code, but I see you are using a markdown parser in `EmailContentParser.php`, for which code would be expected to be either between single backtick (`) or triple backticks (```) to automatically receive `pre` tags from the parser. I do not believe that many post code with markdown formatting in mind.

**Comment by mnapoli** [comment] 2017-01-16 07:18
@tomzx yes but the issue is that the email displays far worse than it should, even without the `pre` tag.

It's interesting that GitHub fails to parse the email correctly too, and it seems to be the `<?php` tag.

Here is a copy-paste of the email content, look at how GitHub format it:

---

Hello All,

In PHP we currently have the ability to type hint classes in method
signatures, however, sometimes it would be useful to convert the items to a
different instance / type.

An example is collections and arrays. If implemented properly, an array and
a collection could be used interchangeably, although a collection may be
preferred. For consistency, having the ability to dynamically cast from an
array to a collection would be very useful.

An idea of how this may look would be:

<?php

class Collection extends ...
{
    protected $items;

    public function __construct(array $items)
    {
        $this->items = $items;
    }

   ...

    public function __cast(array $items) : Collection
    {
        return new static($items)
    }
}

**Comment by mnapoli** [comment] 2017-01-16 07:19
Now if I remove the `<?php` tag:

---


Hello All,

In PHP we currently have the ability to type hint classes in method
signatures, however, sometimes it would be useful to convert the items to a
different instance / type.

An example is collections and arrays. If implemented properly, an array and
a collection could be used interchangeably, although a collection may be
preferred. For consistency, having the ability to dynamically cast from an
array to a collection would be very useful.

An idea of how this may look would be:

<?php

class Collection extends ...
{
    protected $items;

    public function __construct(array $items)
    {
        $this->items = $items;
    }

   ...

    public function __cast(array $items) : Collection
    {
        return new static($items)
    }
}

**Comment by tomzx** [comment] 2017-01-16 13:25
@mnapoli My guess is that in all cases the <?php is not escaped and considered an opening tag.

In all my tests on http://pandoc.org/try/ (using the 4 flavors available there), you can tell that 

```
<?php

class Collection extends ...
{
    protected $items;

    public function __construct(array $items)
    {
        $this->
```

is considered as an XML element by the parser as the next line is

```
<p>items = $items; }</p>
```

which basically indicates the parser started reading the code as if it was regular text again (as it leaves XML alone).

What would be an easy "fix" (may not cover everything), would be to simply go through the email before handing it over to the markdown parser and replacing `<?php` with `\<?php`.

**Comment by mnapoli** [comment] 2017-01-16 18:57
Turning `<?php` into `&lt;?php` sounds like a good idea, but it seems it should already be the case: https://github.com/mnapoli/externals/blob/master/tests/Email/EmailContentParserTest.php#L83-L102 Anyway we can add this email as a test case and check what happens.

> I'm curious, what are the benefits of using markdown to parse those emails? Is it mostly to format lists and automatically create paragraphs?

Yes, as well as code blocks, quotations, etc. Some people even use inline code highlighting in their emails. This is a double bladed sword, it works very well for 80% of the emails, and quite bad for 20%. But I still consider that worth it, and that what makes this reader different (and IMO better) from the other ones. Some people are even using more Markdown in their emails to the list because of externals.io :)

**Comment by mnapoli** [comment] 2017-07-11 15:50
Other occurrences:

- https://externals.io/message/99753
- https://externals.io/message/99834

**Comment by cryode** [comment] 2017-07-11 22:03
The primary issue appears to be the CommonMark specification + lack of closing `?>` tag. http://spec.commonmark.org/0.27/#html-block

> HTML Block: a group of lines that is treated as raw HTML (and will not be escaped in HTML output).
> 
> It ends with the first subsequent line that meets a matching end condition, **or the last line of the document** or other container block), **if no line is encountered that meets the end condition.**

You can replicate the output by pasting the email body source into the [CommonMark online tester](http://spec.commonmark.org/dingus/).

**Closed** 2017-07-28 18:04 UTC

**Comment by mnapoli** [comment] 2017-07-28 18:09
I've launched the script to reparse all emails (100,000), it will take some time.

However all threads mentioned here have been reparsed and I confirm that the bug is resolved \o/

**Comment by mnapoli** [comment] 2017-07-28 18:09
For example:

Before:

![capture d ecran 2017-07-28 a 20 07 41](https://user-images.githubusercontent.com/720328/28730480-a75e1710-73d0-11e7-90d3-908c92257238.png)

After:

![capture d ecran 2017-07-28 a 20 07 50](https://user-images.githubusercontent.com/720328/28730485-aa7bafc0-73d0-11e7-9447-66f385405e7e.png)
